# Generated by Django 4.2.5 on 2023-09-12 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("artapp", "0004_artist_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist_profile",
            name="picture1",
            field=models.ImageField(default="default.png", upload_to="artist_pic/"),
        ),
        migrations.AlterField(
            model_name="artist_profile",
            name="picture2",
            field=models.ImageField(default="default.png", upload_to="artist_pic/"),
        ),
        migrations.AlterField(
            model_name="artist_profile",
            name="picture3",
            field=models.ImageField(default="default.png", upload_to="artist_pic/"),
        ),
        migrations.CreateModel(
            name="Book_Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=100)),
                ("venue", models.CharField(max_length=100)),
                ("time", models.CharField(max_length=100)),
                ("event", models.CharField(max_length=100)),
                ("crowd_strength", models.PositiveIntegerField()),
                ("artist_confirmation", models.BooleanField(default=False)),
                ("payment_status", models.PositiveIntegerField(default=False)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artapp.artist_profile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="artapp.user"
                    ),
                ),
            ],
        ),
    ]
